version: 2

jobs:
  build:
    docker:
      - image: alpine:3.12.3

    steps:
      - checkout

      - run:
          name: Install Required Tools
          command: |
            sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories
            echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories
            apk add --no-cache bash py3-pip py3-virtualenv shellcheck shfmt

      - run:
          name: Set Up Virtualenv
          command: |
            python3 -m venv venv
            echo "source venv/bin/activate" >> $BASH_ENV
            source venv/bin/activate
            pip3 install -e .[dev]

      - run:
          name: Format
          command: ./scripts/format.sh check

      - run:
          name: Lint
          command: ./scripts/lint.sh

      - run:
          name: Test
          command: ./scripts/test.sh

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results
