version: 2

jobs:
  build:
    docker:
      - image: archlinux:base-devel

    steps:
      - checkout

      - run:
          name: Install Required Tools
          command: |
            pacman -Sy --noconfirm \
              python python-pip python-virtualenv \
              lcms2 libtiff openjpeg2 libimagequant libxcb \
              shellcheck shfmt

      - run:
          name: Set Up Virtualenv
          command: |
            python -m venv venv
            echo "source venv/bin/activate" >> $BASH_ENV
            source venv/bin/activate
            pip install --upgrade pip wheel
            pip install -e .[dev]

      - run:
          name: Format
          command: ./scripts/format.sh check

      - run:
          name: Lint
          command: ./scripts/lint.sh

      - run:
          name: Test
          command: ./scripts/test.sh

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results
